# Generated by Django 5.1.7 on 2025-03-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaiverity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaiverity',
            name='description',
        ),
    ]
