# Generated by Django 5.1.7 on 2025-03-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_remove_chaiverity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaiverity',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
