# Generated by Django 5.1.7 on 2025-03-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0005_chaiverity_description_alter_chaiverity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaiverity',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
