# Generated by Django 5.1.7 on 2025-03-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0006_chaiverity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaiverity',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chaiverity',
            name='type',
            field=models.CharField(choices=[('MASALA', 'Masala'), ('GINGER', 'Ginger'), ('KIWI', 'Kiwi'), ('PLAIN', 'Plain'), ('ELACHI', 'Elachi')], max_length=10),
        ),
    ]
