# Generated by Django 5.1.7 on 2025-03-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0007_alter_chaiverity_name_alter_chaiverity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaiverity',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
